# Generated by Django 3.1 on 2020-09-17 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('sku', models.AutoField(primary_key=True, serialize=False)),
                ('date_registered', models.DateField(auto_now_add=True)),
                ('product_name', models.CharField(max_length=30)),
                ('product_brand', models.CharField(max_length=30)),
                ('product_Color', models.CharField(choices=[('B', 'Black'), ('W', 'White'), ('R', 'Red'), ('G', 'Green'), ('Y', 'Yellow'), ('B', 'Blue'), ('P', 'Purple'), ('O', 'Orange')], max_length=1)),
                ('product_size', models.CharField(max_length=30)),
                ('product_dimension', models.CharField(max_length=30)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('num_items', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
