# Generated by Django 3.1.1 on 2020-09-24 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200924_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='profile_picture',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='images',
            name='profile_picture',
            field=models.FileField(null=True, upload_to='static/apps/product/img/profile_pictures'),
        ),
    ]
