# Generated by Django 3.1.1 on 2020-09-24 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20200924_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='product',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='images',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/apps/product/img/profile_pictures'),
        ),
    ]
