# Generated by Django 3.1 on 2020-09-17 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='static/apps/product/img/profile_pictures'),
        ),
    ]
