# Generated by Django 3.1.1 on 2020-10-01 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20200924_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('B', 'Black'), ('W', 'White'), ('R', 'Red'), ('G', 'Green'), ('Y', 'Yellow'), ('P', 'Purple'), ('O', 'Orange')], max_length=1),
        ),
    ]
