# Generated by Django 3.1.1 on 2020-10-08 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20201008_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cash_received',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='order',
            name='change',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9),
        ),
    ]
