# Generated by Django 3.1.1 on 2020-10-08 18:43

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(max_length=30)),
                ('profile_picture', models.ImageField(blank=True, upload_to='static/apps/customer/img/profile_pictures/')),
                ('street', models.CharField(default='', max_length=50)),
                ('barangay', models.CharField(default='', max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('province', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=4)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1)),
                ('birth_date', models.DateField()),
                ('status', models.CharField(choices=[('S', 'Single'), ('M', 'Married'), ('W', 'Widowed'), ('D', 'Divorced')], max_length=1)),
                ('spouse_name', models.CharField(blank=True, max_length=70)),
                ('spouse_occupation', models.CharField(blank=True, max_length=30)),
                ('number_of_children', models.PositiveIntegerField(default=0)),
                ('mother_name', models.CharField(blank=True, max_length=70)),
                ('mother_occupation', models.CharField(blank=True, max_length=30)),
                ('father_name', models.CharField(blank=True, max_length=70)),
                ('father_occupation', models.CharField(blank=True, max_length=30)),
                ('height', models.PositiveIntegerField(verbose_name='Height (cm)')),
                ('weight', models.PositiveIntegerField(verbose_name='Weight (kg)')),
                ('religion', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='customer.person')),
                ('date_registered', models.DateField(auto_now_add=True)),
                ('date_modified', models.DateField(auto_now=True)),
            ],
            bases=('customer.person',),
        ),
    ]
