# Generated by Django 3.1 on 2020-09-15 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(max_length=30)),
                ('profile_picture', models.ImageField(upload_to='static/apps/customer/img/profile_pictures/')),
                ('city', models.CharField(max_length=50)),
                ('province', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=4)),
                ('country', models.CharField(max_length=30)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('birth_date', models.DateField()),
                ('status', models.CharField(choices=[('S', 'Single'), ('M', 'Married'), ('W', 'Widowed'), ('D', 'Divorced')], max_length=1)),
                ('spouse_name', models.CharField(blank=True, max_length=70)),
                ('spouse_occupation', models.CharField(blank=True, max_length=30)),
                ('number_of_children', models.PositiveIntegerField(default=0)),
                ('father_name', models.CharField(max_length=70)),
                ('father_occupation', models.CharField(max_length=30)),
                ('mother_name', models.CharField(max_length=70)),
                ('mother_occupation', models.CharField(max_length=30)),
                ('height', models.PositiveIntegerField(verbose_name='Height (cm)')),
                ('weight', models.PositiveIntegerField(verbose_name='Weight (kg)')),
                ('religion', models.CharField(max_length=30)),
            ],
        ),
    ]
