# Generated by Django 3.1 on 2020-09-19 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20200917_1304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='sex',
            new_name='gender',
        ),
    ]
