# Generated by Django 3.1 on 2020-09-23 06:54

from django.db import migrations, models
import django_countries.fields
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20200919_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='person',
            name='profile_picture',
            field=stdimage.models.StdImageField(blank=True, upload_to='static/apps/customer/img/profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='person',
            name='religion',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
