# Generated by Django 3.1.1 on 2020-09-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_auto_20200923_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='father_name',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='person',
            name='father_occupation',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='person',
            name='mother_name',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='person',
            name='mother_occupation',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='person',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='static/apps/customer/img/profile_pictures/'),
        ),
    ]
